export class Constants {
  //隐私政策
  public static App_Pravicy: string = "agree_pravicy"
  //数据key
  public static Key_BookId: string = "book_id"
  public static Key_ChapterId: string = "type_id"
  public static Key_NoteId: string = "note_id"
  //首页菜单key
  public static Menu_ListView: string = "list_view"
  public static Menu_SortType: string = "sort_type"
  //设置
  public static Setting_LockType: string = "lock_type"
  public static Setting_Pattern: string = "pattern_lock"
  //编辑器
  public static Editor_Wallpaper: string = "edit_bg"
  public static Editor_TextAlign: string = "text_align"
  public static Editor_TitlteSize: string = "text_size"
  public static Editor_ContentSize: string = "content_size"
  public static Editor_ContentPadding: string = "content_padding"
  public static Editor_WordPadding: string = "word_padding"
  public static Editor_LinePadding: string = "line_padding"
  //通信id
  public static Message_Delete_Current_Edit: number = 109
  public static Message_Book_Select: number = 110
  public static Message_Editor_Wallpaper: number = 111
  public static Message_Editor_Setting: number = 112
  public static Message_Restore: number=113
}